#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat May 22 00:10:53 2021

@author: tsar
"""

from sqlalchemy import create_engine
from payment_system_create_base import bills
engine = create_engine('sqlite:///accounts.db', echo=True)


def newUser(id_user):
    ins = bills.insert()
    ins = bills.insert().values(id = id_user,
                                digits = 0,
                                currency = 'RUB')
    conn = engine.connect()
    conn.execute(ins)
    
newUser(1)